sudo: required
services:
  # Add docker as dependecy
  - docker

before_install:
  # Build images for testing
  - docker build -t markweldonbrewer/cl-client-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests
  - docker run -e CI=true markweldonbrewer/cl-client-test npm test -- --coverage

after_success:
  - docker build -t markweldonbrewer/cl-client ./client
  - docker build -t markweldonbrewer/cl-nginx ./nginx
  - docker build -t markweldonbrewer/cl-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push markweldonbrewer/cl-client
  - docker push markweldonbrewer/cl-nginx
  - docker push markweldonbrewer/cl-server
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: component-library
  env: ComponentLibrary-env
  bucket_name: elasticbeanstalk-us-east-2-496054991405
  bucket_path: component-library
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
