sudo: required
services:
  # Add docker as dependecy
  - docker

before_install:
  # Build images for testing
  - docker build -t markweldonbrewer/cl-client-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests
  - docker run -e CI=true markweldonbrewer/cl-client-test npm test -- --coverage

after_success:
  - docker build -t markweldonbrewer/cl-client -f ./client
  - docker build -t markweldonbrewer/cl-nginx -f ./nginx
  - docker build -t markweldonbrewer/cl-server -f ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push markweldonbrewer/cl-client
  - docker push markweldonbrewer/cl-nginx
  - docker push markweldonbrewer/cl-server
