version: '3'
services:
  mongo:
    restart: always
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=componentLibraryDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_PASSWORD=admin
      - MONGO_USERNAME=admin
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
