version: '3'
services:
  mongo:
    restart: always
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=componentLibraryDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
  sever:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_PASSWORD=admin
      - MONGO_USERNAME=admin
